#!/bin/bash


# ----------------------------------
# Define variables
# ----------------------------------

# Colors name
COLOR_BLACK="\033[0;30m"
COLOR_RED="\033[0;31m"
COLOR_YELLOW="\033[0;33m"
COLOR_GREEN="\033[0;32m"
COLOR_RESET="\033[0m"

# ----------------------------------
# Function
# ----------------------------------

pause(){
	read -p "Press [Enter] key to continue..." fackEnterKey
}


upgradeAndClean(){
	sudo apt-get update
	sudo apt-get upgrade
	sudo apt-get dist-upgrade
	sudo apt-get autoclean
	sudo apt-get autoremove

	# Test if a reboot is needed
	if [ -f /var/run/reboot-required ]; then
		echo -e $COLOR_RED'Reboot required!'$COLOR_RESET
	fi

	pause
}

REPOSITORIES_LIST=(
".dotfiles"
".scripts"
".vim"
".fzf"
)

updateRepositories(){
	# TODO test if 'git pull' failes
	for i in "${REPOSITORIES_LIST[@]}"; do
		(cd ~/$i/ && git pull origin master)
		if [[ "$i" == *".fzf"* ]]; then
			~/.fzf/install
		fi
	done

	pause
}

# Menu headlines
SYSTEM_MAINTENANCE="${COLOR_GREEN}SYSTEM MAINTENANCE${COLOR_RESET}"
BUNDLES="${COLOR_GREEN}BUNDLES${COLOR_RESET}"
PLACEHOLDER="${COLOR_GREEN}SOMETHING ELSE${COLOR_RESET}"

show_menu(){
	clear
	echo    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo    "          MASTERSCRIPT          "
	echo    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo -e "${SYSTEM_MAINTENANCE}"
	echo    "1. Clean And Upgrade System"
	echo    "2. Update My Repositories"
	echo    "3. Sync google drive"
	echo    ""
	echo -e "${BUNDLES}"
	echo    "4. (1 and 2)"
	echo    " - Clean And Upgrade System"
	echo    " - Update My Repositories  "
	echo    ""
	echo -e "${PLACEHOLDER}"
	echo    "5. Help"
	echo    "6. Exit"
	echo    ""
}

read_options(){
	local choice
	read -p "Enter choice: " choice
	case $choice in
		1) upgradeAndClean ;;
		2) updateRepositories;;
		3) (cd ~/google-drive/ && grive && pause);;
		4) upgradeAndClean && updateRepositories;;
		5) echo -e "${COLOR_YELLOW}Help not written yet${COLOR_RESET}" && sleep 2;;
		6) exit 0;;
		*) echo -e "${COLOR_RED}Error:${COLOR_RESET} invalid input" && sleep 2
	esac
}


# -----------------------------------
# Main logic - infinite loop
# ------------------------------------
while true
do
	show_menu
	read_options
done
