#!/bin/bash

tmux start-server
tmux source-file ~/.tmux.conf

SESSIONNAME="main"
tmux has-session -t $SESSIONNAME &> /dev/null

# send keys to specifk panes
# https://superuser.com/questions/492266/run-or-send-a-command-to-a-tmux-pane-in-a-running-tmux-session

if [ $? != 0 ]
then
	tmux new-session -d -s $SESSIONNAME

	# htop
	tmux new-window -t $SESSIONNAME:1 -n htop
	#################################################

	tmux send-keys -t $SESSIONNAME:1 "htop" C-m
	tmux split-window -t $SESSIONNAME:1 -h
	tmux send-keys -t $SESSIONNAME:1 "sleep 5" Enter "tmux resize-pane -x 79 && watch -n 2 nvidia-smi" C-m
	#tmux send-keys -t $SESSIONNAME:1.2 "tmux resize-pane -x 79" C-m
	#tmux send-keys -t $SESSIONNAME:1.2 "watch -n 2 nvidia-smi" C-m
	tmux split-window -t $SESSIONNAME:1 -v
	tmux send-keys -t $SESSIONNAME:1 "watch -n 2 sensors" C-m


	# dev
	#tmux new-window -t $SESSIONNAME:2 -n dev
	#################################################

	# vim
	#tmux rename-window 'dev'
	#tmux select-window -t vim:1
	#tmux send-keys -t $SESSIONNAME:2 "cd .save/" C-m

	# right terminal
	#tmux split-window -t 1 -h
	#tmux resize-pane -x 50
	#tmux send-keys -t $SESSIONNAME:2 "cd .save/" C-m
	#tmux send-keys -t $SESSIONNAME:2 C-l

	# button terminal
	#tmux split-window -t 1 -v
	#tmux resize-pane -y 5
	#tmux send-keys -t $SESSIONNAME:2 "cd .save/" C-m
	#tmux send-keys -t $SESSIONNAME:2 C-l

	# select vim pane
	#tmux select-pane -t 1


	# dotfiles
	tmux new-window -t $SESSIONNAME:2 -n dotfiles
	#################################################

	#tmux send-keys -t $SESSIONNAME:3 "vim .vimrc" C-m
	#tmux send-keys -t $SESSIONNAME:3 ":tabedit .bashrc" C-m
	#tmux send-keys -t $SESSIONNAME:3 ":tabedit .tmux.conf" C-m
	#tmux send-keys -t $SESSIONNAME:3 ":vsplit ~/.scripts/stmux" C-m


	# masterscript
	tmux new-window -t $SESSIONNAME:3 -n masterscript
	#################################################

	tmux send-keys -t $SESSIONNAME:3 "masterscript" C-m


fi

tmux attach -t $SESSIONNAME
