#!/bin/bash

SESSIONNAME="main"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
 then
    tmux new-session -s $SESSIONNAME -n masterscript -d
    tmux send-keys -t $SESSIONNAME "masterscript" C-m
    tmux new -s $SESSIONNAME -n mywindow
fi

tmux attach -t $SESSIONNAME
